<h1><?= "My account: Overview" ?></h1>
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <?= $this->partial('mkdf/core/partial/account-features', ['features' => $features] ) ?>
        </div>
        <div class="col-md-9">
            <table class="table table-bordered">
                <!--
                <tr>
                    <th>ID:</th>
                    <td><?= $this->escapeHtml($user->getId()) ?></th>
                </tr>
                -->
                <tr>
                    <th>E-mail:</th>
                    <td><?= $this->escapeHtml($user->getEmail()) ?></th>
                </tr>
                <tr>
                    <th>Full Name:</th>
                    <td><?= $this->escapeHtml($user->getFullName()) ?></td>
                </tr>
                <tr>
                    <th>Date Created:</th>
                    <td><?= $this->escapeHtml($user->getDateCreated()) ?></td>
                </tr>
                <tr>
                    <th>Status:</th>
                    <td><?= $this->escapeHtml($user->getStatusAsString()) ?></td>
                </tr>
                <?php if ($user->getIsAdmin()): ?>
                <tr>
                    <th>Admin:</th>
                    <td>Yes</td>
                </tr>
                <?php endif; ?>
            </table>
        </div>
    </div>
</div>



