<h1>Users</h1>

<?= $this->partial('mkdf/core/partial/actions', $actions); ?>

<form action="<?= $this->url( 'users', ['action'=>'index'],[]); ?>" method="get" id="dataset-search" name="dataset-search">
    <div class="form-group">
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="basic-addon1"><i class="fas fa-search"></i></span>
            </div>
            <?php if($txt_search != ""): ?>
                <input type="text" name="txt" id="txt" class="form-control" aria-label="Search" aria-describedby="basic-addon1" value="<?= $txt_search ?>">
            <?php else: ?>
                <input type="text" name="txt" id="txt" class="form-control" placeholder="Search" aria-label="Search" aria-describedby="basic-addon1">
            <?php endif; ?>
        </div>
    </div>
    <!--<button type="submit" class="btn btn-primary">Submit</button>-->
</form>

    <?php
    if ($txt_search != ""):
    ?>
        <div class="row">
            <div class="col-md-12 text-center">
                <em><i class="fas fa-search"></i> Searching: <?= $txt_search ?></em><br />
            </div>
        </div>
    <?php
    endif;
    ?>

<table class="table table-bordered">

   <tr class="table-active">
        <th>ID</th>
        <th>E-mail</th>
        <th>Full Name</th>
        <th>Date Created</th>
        <th>Status</th>
        <th>Admin</th>
    </tr>
    
    <?php foreach ($users as $user): ?>
    
    <tr>
        <td><?= $this->escapeHtml($user->getId()); ?></td>
        <td>
            <a href="<?= $this->url('users', ['action'=>'view', 'id'=>$user->getId()]); ?>">
                <?= $this->escapeHtml($user->getEmail()); ?>
            </a> 
        </td>
        <td><?= $this->escapeHtml($user->getFullName()); ?></a> 
        </td>
        <td><?= $this->escapeHtml($user->getDateCreated()); ?></td>        
        <td><?= $this->escapeHtml($user->getStatusAsString()); ?></td>
        <td><?= $user->getIsAdmin() ? "Yes" : "No" ; ?>
    </tr>
        
    <?php endforeach; ?>   
    
</table>
<?= $this->paginationControl($users,
        'Sliding',
        'application/partial/paginator',
        [
            'route' => 'users',
            'url_params' => $url_params
        ]); ?>



