<?php
$this->headTitle('Thank You');
?>

<div class="row">
<div class="col-md-offset-4 col-md-5">
<h1>Reset Password</h1>

<?php if ($id=='sent'): ?>
<p>
    If the supplied email address matches an account on the MK Data Hub, the user will be notified with password reset instructions now.
</p>
<?php elseif ($id=='invalid-email'): ?>
<p>
    There is no user with such an email or the user is inactive.
</p>
<?php elseif ($id=='set'): ?>
<p>
    Your new password has been set successfully.
</p>
<p>
    Return to <a href="<?= $this->url('login'); ?>">login page</a>.
</p>
<?php elseif ($id=='failed'): ?>

    Invalid reset key or it may have expired. Please return 
    <a href="<?= $this->url('reset-password') ?>">here</a> and try reset your password again.
</p>
<?php endif; ?>
</div>
</div>    